In [1]:
import cv2

In [2]:
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_COLOR)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_UNCHANGED)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_COLOR)
cv2.imshow('input window',img)
status = cv2.imwrite('C:/Users/Udara Chamikara/Desktop/IUP/2.jpg',img)
print("Image successfully saved ?", status)
cv2.waitKey()
cv2.destroyAllWindows()

Image successfully saved ? True


In [7]:
# For color Image

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_COLOR)
px = img[50,100]  # pixsel cordinates (x,y)
print(px) # Blue Green Red ( 33 172 145 )
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

[ 33 172 145]


In [8]:
# For Grayscale Image 

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_GRAYSCALE)
px = img[50,100]  # pixsel cordinates (x,y)
print(px) # single value ( 148 )
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

148


In [2]:
#For modify image (color image)
import cv2
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_COLOR)
px = img[50,100]  # pixsel cordinates (x,y)
print(px) # Blue Green Red ( 33 172 145 )
img [50,100] = [255,255,255] # how to change pixel value
print(img[50,100]) # print the pixel value
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows() 

[ 33 172 145]
[255 255 255]


In [10]:
#for modify image ( Grayscale Image)

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",cv2.IMREAD_GRAYSCALE)
px = img[50,100]  # pixsel cordinates (x,y)
print(px) # single value ( 148 )
img[50,100] = 255
print(img[50,100])
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

148
255


In [11]:

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
print(img.shape) # Size = 133 x 150 and colors = 3
print(img.size)
print(img.dtype)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

(113, 150, 3)
50850
uint8


In [12]:

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",0)
print(img.shape) # Size = 133 x 150 single color channels
print(img.size)
print(img.dtype)
cv2.imshow('input window',img)
cv2.waitKey()
cv2.destroyAllWindows()

(113, 150)
16950
uint8


In [3]:
import cv2
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
cv2.imshow('input window',img)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('output window',gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import cv2
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
cv2.imshow('input window',img)

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#cv2.imshow('output window 1',gray)

res,binary = cv2.threshold(gray,120, 255, cv2.THRESH_BINARY)
#cv2.imshow('output window 2',binary)

Gray = cv2.split(img)
cv2.imshow('split imsge', Gray)

cv2.waitKey()
cv2.destroyAllWindows()

TypeError: Expected Ptr<cv::UMat> for argument 'mat'

In [1]:
import cv2

img = cv2.imread('C:/Users/Udara Chamikara/Desktop/IUP/1.jpg', 1)
[B, G, R] = cv2.split(img)
cv2.imshow('Blue Image' , B)
cv2.imshow('Green Image', G)
cv2.imshow('Red Image', R)

mergeimg = cv2.merge([B, G, R])
cv2.imshow('Merged Image', mergeimg)

cv2.waitKey()
cv2.destroyAllWindows()



In [ ]:
import cv2
import numpy
from PIL import Image

img = cv2.imread('C:/Users/Udara Chamikara/Desktop/IUP/1.jpg', 1)
cv2.imshow('Input Image', img)

imge = Image.open('C:/Users/Udara Chamikara/Desktop/IUP/1.jpg')

rotateimg = imge.rotate(45)
rotateimg.save('C:/Users/Udara Chamikara/Desktop/IUP/Rotate Image1.jpg', expand = True)

cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
import cv2
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
cv2.imshow('input window',img)

dsize=(400, 400)

img1 = cv2.resize(img, dsize)
cv2.imshow('Resize Image', img1)

cv2.waitKey()
cv2.destroyAllWindows()

In [15]:
import cv2
img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)
cv2.imshow('input window',img)

center_coordinates = (70, 70)

radious = 50

color = (255,0,0)

thickness = 9

circle = cv2.circle(img, center_coordinates, radious, color, thickness )

cv2.imshow('Circle Image', circle)

cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
import cv2

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)

dsize = (400, 400)

imge = cv2.resize(img, dsize)
cv2.imshow('input window',imge)

start_point = (20,20)

end_point = (30, 300)

tickness = 3

rectangle = cv2.rectangle(imge, start_point, end_point , tickness)

cv2.imshow('Rectangle Image', rectangle)

cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
import cv2

img = cv2.imread("C:/Users/Udara Chamikara/Desktop/IUP/1.jpg",1)

dsize = (400, 400)

imge = cv2.resize(img, dsize)
cv2.imshow('input window',imge)

start_point = (20,300)

end_point = (200, 300)

color = (178, 153, 67)

tickness = 3

line = cv2.line(imge, start_point, end_point , color, tickness)

cv2.imshow('Line Image', line)

cv2.waitKey()
cv2.destroyAllWindows()